import {
    Activity,
    TrendingUp,
    TrendingDown,
    DollarSign,
    Zap,
    Database,
    Server,
    Wifi,
    WifiOff,
    ChevronUp,
    ChevronDown,
    LineChart,
    BarChart3,
    Clock,
    RefreshCw,
    Cpu,
    Play,
    Square,
    Settings,
    Plus,
    Trash2,
    Search,
    Menu,
    X,
    LogOut
} from 'lucide-react';

export const Icons = {
    activity: Activity,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    dollarSign: DollarSign,
    zap: Zap,
    database: Database,
    server: Server,
    wifi: Wifi,
    wifiOff: WifiOff,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    lineChart: LineChart,
    barChart: BarChart3,
    clock: Clock,
    refresh: RefreshCw,
    cpu: Cpu,
    play: Play,
    square: Square,
    settings: Settings,
    plus: Plus,
    trash: Trash2,
    search: Search,
    menu: Menu,
    x: X,
    logout: LogOut,
};

export type IconName = keyof typeof Icons;
