import {
    Activity,
    TrendingUp,
    TrendingDown,
    DollarSign,
    Zap,
    Database,
    Server,
    Wifi,
    WifiOff,
    ChevronUp,
    ChevronDown,
    LineChart,
    BarChart3,
    Clock,
    RefreshCw,
    Play,
    Square,
    Pause,
    Target,
    FileText,
    AlertCircle,
    CheckCircle,
    XCircle
} from 'lucide-react';

export const Icons = {
    activity: Activity,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    dollarSign: DollarSign,
    zap: Zap,
    database: Database,
    server: Server,
    wifi: Wifi,
    wifiOff: WifiOff,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    lineChart: LineChart,
    barChart: BarChart3,
    clock: Clock,
    refresh: RefreshCw,
    play: Play,
    stop: Square,
    pause: Pause,
    target: Target,
    fileText: FileText,
    alertCircle: AlertCircle,
    checkCircle: CheckCircle,
    xCircle: XCircle,
};

export type IconName = keyof typeof Icons;

